### ISSUE TITLE
Adding contributers into readme.md

### ISSUE THREAD

**Issue by sb-decoder** [DiyaVj/Profile-Card-Collection#97]
if you want this feature in your readme.md then assign me this task.

**Comment by sb-decoder** [comment]
and I think if profile-card-collection's  added to README.md then it looks good.

**Comment by DiyaVj** [comment]
Hey @sb-decoder!
Are you talking about adding the profile card collection folder's readme to the main readme?

**Comment by sb-decoder** [comment]
Yeah!

**Comment by sb-decoder** [comment]
And also all contributer's profile images into your readme.md file

**Comment by DiyaVj** [comment]
It looks interesting. But is it possible to make it easier for contributors as well? so that they do not face any difficulty while contributing to the main readme.

**Comment by sb-decoder** [comment]
Then you have to add some instructions by which they change the main.readme

**Comment by DiyaVj** [comment]
Ok! I'll do it. And for those who have already contributed, we have to update their details also.

**Comment by sb-decoder** [comment]
Ok , if you want any help then tell me. Thanks

**Comment by DiyaVj** [comment]
I appreciate your enthusiasm and going to hand you this issue.

**Comment by sb-decoder** [comment]
Ok will do this soon.

**Comment by DiyaVj** [comment]
Thank you!✨

**Comment by BWsix** [comment]
@DiyaVj
what about we use something like https://contrib.rocks to generate image of contributors automatically?

**Comment by DiyaVj** [comment]
Hey @BWsix!
This is an amazing website and it can save us a lot of time too. We can use it on the main readme. Thank you for sharing✨

**Comment by BWsix** [comment]
@DiyaVj 
Should I just make a PR to add the contributor image? @sb-decoder have not yet make a PR on this.

**Comment by sb-decoder** [comment]
I will do it.

**Comment by BWsix** [comment]
I see!

**Comment by DiyaVj** [comment]
I have an idea. We can add kudos to the contributors on the main readme (using the website provided by @BWsix ) and we can add their profile image with their profile card link inside the readme of the profile card collection folder (as @sb-decoder wants to do). This will help in reducing the cluster on the main readme and also help us to organize files and folders. What do you think about it?

**Comment by sb-decoder** [comment]
Yeah! That's a great idea.

**Comment by BWsix** [comment]
So the readme will look like this?
- the rest of the readme we currently have
- profile card collection folder
- contributors image generated by the website

**Comment by sb-decoder** [comment]
No, we just have to  change the readme of profile card collection folder . Am I right @DiyaVj ?

**Comment by BWsix** [comment]
Oh you are right, I misunderstood his meaning😅

**Comment by BWsix** [comment]
@sb-decoder So I should go ahead and make a pull request on the main readme then.

**Comment by DiyaVj** [comment]
Everything will be the same. But
* Only the main readme will have kudos to the contributors and
*  The profile-card-collection readme will include images of the contributors along with their profile card link

**Comment by sb-decoder** [comment]
Ok I will do it by today.

**Comment by BWsix** [comment]
@DiyaVj I see. I made a PR for main readme. Let me know if there's anything that needs to be added!

**Comment by DiyaVj** [comment]
Ok!
